---
title: "Publications and Presentations" 
---

# Peer Reviewed Articles

1.  **Hwang IM**, Rayos del Sol S, Jenkins SM, Bryant SA, Gardner BB, McGahan P, Chen J. “Open Peroneal Tendon Stabilization With Fibular Groove Deepening” Arthrosc Tech. March 2022; 11(3): e347-e351. PMID: 35256974

2. Jenkins SM, **Hwang IM**, Rayos Del Sol S, Guzman AJ, Dela Rueda T, McGahan P, Chen J. “Subpectoral Biceps Tenodesis Using an All-Suture Anchor” Arthrosc Tech. April 2022; 11(4): e555-e562. PMID: 32489840

# Book Chapters 

1. **Hwang IM**, Lou XA, Toubian AA, Kamei DT. BioSensing, Theranostics, and Medical Devices. Singapore: Springer; 2022. Chapter 4, Biosensor-Based Point-of-Care Devices: Metabolites and Pulse Oximetry; p. 83-104.

2. **Hwang IM**, Cantu CM, Chawla R, Kamei DT. BioSensing, Theranostics, and Medical Devices. Singapore: Springer; 2022. Chapter 5, Biosensor-Based Point-of-Care Devices: Detection of Infectious Diseases and Cancer; p. 105-132.

# Poster Presentations 
1. Bhalotia A, Nittayacharn P, Cheplyansky A, Nidhiry A, Mehta M, Iyer A, Hariharan S, **Hwang IM**, Exner AA, Karathanasis E. “Ultrasound-Mediated Gene Therapy: Pre-Sensitization to Cure”, The Biomedical Engineering Society Annual Meeting, Baltimore, MD (2024). (Poster presented by Bhalotia, A).

2. **Hwang IM**, Lee E, Azimi M, Emmel G, Falktoft C, Kamei DT. “AutoAeroAssay: Automated Device for Collection and Detection of Airborne Pathogens”, Los Angeles, CA (2019). (Poster presented by Hwang, IM)

# Oral Abstract Presentations 
1.	Cheung SF, Yang EJ, **Hwang IM**, Carson M, Wu BM, Kamei DT. “Single step isothermal DNA sample preparation with paper-based amplification” The Biomedical Engineering Society Annual Meeting, Atlanta, Georgia (2018) (Presented by Cheung, SF)